@echo Construyendo Zeus.Extras.dll...
@\Trabajo\Tools\ilmerge /t:library /out:Zeus.Extras.dll /closed AxInterop.ShockwaveFlashObjects.dll ExcelUtil.dll Interop.ShockwaveFlashObjects.dll MigraDoc.DocumentObjectModel.dll MigraDoc.Rendering.dll Mono.Security.dll Npgsql.dll PdfSharp.dll ZedGraph.dll PdfSharp.Charting.dll
