//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaEquipos {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PRUEBA DE EQUIPOS DE LA INSTITUCIÓN ({0} HORAS)")]
        public string Titulo {
            get {
                return ((string)(this["Titulo"]));
            }
            set {
                this["Titulo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BUENOS DÍAS")]
        public string Saludo {
            get {
                return ((string)(this["Saludo"]));
            }
            set {
                this["Saludo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TRANSMITE LA CENTRAL DE TELECOMUNICACIONES Y ALARMAS DEL CUERPO DE BOMBEROS METRO" +
            "POLITANO SUR, EN SU PRUEBA DE EQUIPOS MÓVILES DE LA INSTITUCIÓN.")]
        public string MensajeInicio {
            get {
                return ((string)(this["MensajeInicio"]));
            }
            set {
                this["MensajeInicio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CENTRAL DE ALARMAS FINALIZA PRUEBA DE SUS EQUIPOS MÓVILES.")]
        public string MensajeTermino {
            get {
                return ((string)(this["MensajeTermino"]));
            }
            set {
                this["MensajeTermino"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UsarCarros {
            get {
                return ((bool)(this["UsarCarros"]));
            }
            set {
                this["UsarCarros"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList CarrosSeleccionados {
            get {
                return ((global::System.Collections.ArrayList)(this["CarrosSeleccionados"]));
            }
            set {
                this["CarrosSeleccionados"] = value;
            }
        }
    }
}
