'GoldParser tool - in support of Field Calculator tool. Brought in from the USU code base
'during merger by Chris M on April 21 2006. Thanks to USU
'for this!

Imports System

' VB.NET Translation of GoldParser, by Reggie Wilbanks <AppDeveloper@starband.net> converted (by hand) from,
' C# Translation of GoldParser, by Marcus Klimstra <klimstra@home.nl>.
' Based on GOLDParser by Devin Cook <http:'www.devincook.com/goldparser>.
Namespace GoldParser
  ' This is a visitor-interface for the parse tree generated by GoldParser.
  ' See the sample project for more information.
  Public Interface IGoldVisitor
   ' Visits the specified <c>Reduction</c>.
    Sub Visit(ByVal r As Reduction)
  End Interface
End Namespace
